-- AlterEnum
ALTER TYPE "ContactType" ADD VALUE 'REMINDER';

-- AlterTable
ALTER TABLE "Contact" ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "observation" DROP NOT NULL;
